### ISSUE TITLE
Level names

### ISSUE THREAD

**Issue by turboxx** [oakslab/ooo-engineering-levels#1]
Can we add level names as well? numbering is nice but that's not more telling, eg: 
E1 - Newbie
E6 - One punch man

**Comment by quibusus** [comment]
We chose no-names because of motivation/ease of use. Everyone perceives junior/newbie as something different.

e.g. a person might see himself as non-newbie, but lacking skills that we require for E2. Classifying him as "newbie" might demotivate him, on the other hand, classifying as E1 will give him a positive "howto".

**Comment by turboxx** [comment]
@quibusus 
Motivation and demotivation can be solved by using proper language. We have the opportunity to set the language as we want so anybody would perceive it as WE define.

I myself won't be able to tell what's the difference between E3 and E4 from top of my head, but from a Skilled and Badass would be much easier.

**Comment by quibusus** [comment]
Closing, for now, we'll get back to this in 6 months, after a few rounds of feedback
